apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/nginx

replicas:
  - name: nginx
    count: 3

patches:
  - path: deployment-patch.yaml

images:
  - name: nginx
    newName: nginx
    newTag: 1.27-alpine
